import Link from "next/link";
import { ArrowLeft, ArrowRight, Banknote, FileCheck2, LockKeyhole, PhoneCall, ShieldAlert } from "lucide-react";
import { getIncident } from "@/lib/store";
import { BANK_PLAYBOOKS, CONTENT_PLAYBOOK, HELPLINE_1930 } from "@/lib/playbooks";
import { notFound } from "next/navigation";
import SiteHeader from "@/components/SiteHeader";
import ActionChecklist from "@/components/ActionChecklist";

export const dynamic = "force-dynamic";

const TRIGGER_LABELS: Record<string, string> = { paid: "money was transferred", otp: "an OTP or PIN was shared", app: "an app was installed", screen: "screen access was granted", images: "private images are involved", id: "identity documents were shared", none: "no immediate harm has been reported" };

export default async function ActPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ trigger?: string }> }) {
  const { id } = await params;
  const { trigger = "none" } = await searchParams;
  const incident = await getIncident(id);
  if (!incident) notFound();
  const isEmergency = ["paid", "otp", "app", "screen", "images"].includes(trigger);
  const isContent = trigger === "images";
  const isMoney = ["paid", "otp"].includes(trigger);

  return <div className="min-h-[100dvh] bg-paper"><SiteHeader /><main id="main-content" className="public-shell py-8 sm:py-12"><div className="stage-rail bg-surface" aria-label="Incident stages">{["Triage", "Tell the story", "Confirm facts", "Act and track"].map((label, index) => <div key={label} className={index === 3 ? "is-active" : ""}><span className="block font-mono text-[10px] font-bold">0{index + 1}</span><span className="mt-1 block text-xs font-bold">{label}</span></div>)}</div><div className="mx-auto mt-8 max-w-4xl"><Link href={`/check/${id}`} className="inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-ink-soft hover:text-service"><ArrowLeft size={16} aria-hidden="true" /> Back to analysis</Link><div className="mt-7 border-b border-line pb-6"><p className="kicker">Step 04 / immediate action board</p><h1 className="mt-3 text-3xl font-bold tracking-[-.04em] text-ink sm:text-4xl">Act in the right order.</h1><p className="mt-3 max-w-2xl text-base leading-7 text-ink-soft">You told us {TRIGGER_LABELS[trigger] ?? "something may have happened"}. The response sequence below keeps containment ahead of paperwork.</p></div>

{isEmergency && <section className="panel mt-7 border-danger/40 bg-danger-soft p-5 sm:p-6"><div className="flex items-start gap-4"><ShieldAlert size={26} className="mt-0.5 shrink-0 text-danger" aria-hidden="true" /><div><p className="kicker text-danger">Containment first</p><h2 className="mt-3 text-2xl font-bold tracking-tight text-ink">Stop. Do exactly this.</h2><p className="mt-2 text-sm leading-6 text-ink-soft">Do not wait for this service to finish processing before calling the official helpline.</p></div></div></section>}

{isMoney && <section className="panel mt-4 border-danger/40 p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-3"><PhoneCall size={22} className="mt-0.5 shrink-0 text-danger" aria-hidden="true" /><div><p className="kicker text-danger">Action 01 / official helpline</p><h2 className="mt-2 text-xl font-bold text-ink">Call 1930 now</h2><p className="mt-2 text-sm leading-6 text-ink-soft">National Cybercrime Financial Helpline, available 24 × 7.</p></div></div><a href="tel:1930" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-[8px] bg-danger px-5 text-sm font-bold text-white hover:bg-command"><PhoneCall size={16} aria-hidden="true" /> 1930</a></div><div className="mt-5 rounded-[8px] bg-paper p-4"><p className="font-mono text-xs leading-6 text-ink">{HELPLINE_1930.script}</p></div><p className="mt-4 text-xs leading-5 text-warning">Call first. Then use this checklist to organise evidence and prepare the response packets.</p></section>}

{isMoney && <section className="panel mt-4 p-5 sm:p-6"><div className="flex gap-3"><Banknote size={21} className="mt-0.5 shrink-0 text-warning" aria-hidden="true" /><div><p className="kicker text-warning">Action 02 / bank containment</p><h2 className="mt-2 text-xl font-bold text-ink">Freeze through your bank</h2><p className="mt-2 text-sm leading-6 text-ink-soft">Choose the relevant institution for the containment playbook and call script.</p></div></div><div className="mt-5 grid gap-2 sm:grid-cols-3">{BANK_PLAYBOOKS.map((bank) => <details key={bank.id} className="panel-tight bg-paper"><summary className="flex min-h-12 cursor-pointer list-none items-center justify-between gap-2 px-3 text-sm font-bold text-ink"><span>{bank.shortName}</span><span className="font-mono text-[10px] text-ink-faint">{bank.helpline}</span></summary><div className="border-t border-line px-3 pb-4 pt-3"><p className="text-xs leading-5 text-ink-soft">{bank.appSteps.join(" · ")}</p><a href={`tel:${bank.helpline.replace(/-/g, "")}`} className="mt-3 inline-flex min-h-10 items-center text-xs font-bold text-service">Call {bank.helpline}</a></div></details>)}</div></section>}

{isContent && <section className="panel mt-4 border-service/30 p-5 sm:p-6"><div className="flex gap-3"><LockKeyhole size={21} className="mt-0.5 shrink-0 text-service" aria-hidden="true" /><div><p className="kicker">Content protection track</p><h2 className="mt-2 text-xl font-bold text-ink">Keep the original image on your device.</h2><p className="mt-2 text-sm leading-6 text-ink-soft">The local fingerprint path is now available from intake. Do not upload intimate images to this service.</p></div></div><div className="mt-5 space-y-4">{CONTENT_PLAYBOOK.steps.map((step, index) => <div key={step.id} className="flex gap-3 border-t border-line pt-4"><span className="font-mono text-xs font-bold text-service">0{index + 1}</span><div><h3 className="text-sm font-bold text-ink">{step.title}</h3><p className="mt-1 text-sm leading-6 text-ink-soft">{step.body}</p></div></div>)}</div></section>}

<section className="panel mt-4 p-5 sm:p-6"><div className="flex gap-3"><FileCheck2 size={21} className="mt-0.5 shrink-0 text-success" aria-hidden="true" /><div><p className="kicker text-success">Action {isMoney || isContent ? "03" : "01"} / evidence</p><h2 className="mt-2 text-xl font-bold text-ink">Preserve evidence before deleting anything.</h2><p className="mt-2 text-sm leading-6 text-ink-soft">Mark each item complete. These checklist actions organise your evidence and do not contact an institution.</p></div></div><div className="mt-5"><ActionChecklist incidentId={id} initialCompleted={incident.completedActions} items={["Export the full conversation", "Save the suspect profile and number", "Record the transaction ID or UTR", "Keep incoming messages and call details", "Record the exact dates and times", "Save the screenshot or receipt"]} /></div></section>

<section className="mt-6"><Link href={`/report/${id}`} className="flex min-h-14 items-center justify-center gap-2 rounded-[10px] bg-service px-5 text-sm font-bold text-white hover:bg-command">Continue to prepared incident packets <ArrowRight size={17} aria-hidden="true" /></Link><p className="mt-3 text-center text-xs text-ink-faint">The next screen uses only the facts you confirmed.</p></section>
</div></main></div>;
}
