"use client";

import { useEffect } from "react";
import { useRakshaLanguage, type RakshaLanguage } from "@/hooks/useRakshaLanguage";

/**
 * Site-wide translation layer for the operational routes (check, track, atlas,
 * act, report, recover, operator). The homepage, header, and emergency bar are
 * translated through React dictionaries; this layer covers the remaining routes
 * by rewriting visible text nodes and re-applying after client-side renders.
 */

const HINDI: Record<string, string> = {
  // Intake (smart input)
  "Step 01 / tell us what happened": "चरण 01 / बताइए क्या हुआ",
  "Paste anything you received. We work out what it is and check it for you.": "आपको जो मिला उसे पेस्ट करें। हम पहचानेंगे कि यह क्या है और आपके लिए जांचेंगे।",
  "Take as long as you need. Nothing is checked until you choose to continue, and you can ask someone you trust to help you with this.": "जितना समय चाहिए लें। जब तक आप आगे बढ़ना नहीं चुनते, कुछ भी जांचा नहीं जाता। आप किसी भरोसेमंद व्यक्ति से मदद ले सकते हैं।",
  "See a worked example": "एक उदाहरण देखें",
  "What did they send you?": "उन्होंने आपको क्या भेजा?",
  "A message, a phone number, a UPI ID, or a link. One box takes all of them.": "मैसेज, फ़ोन नंबर, UPI ID या लिंक। एक ही बॉक्स में सब चलेगा।",
  "Speak instead": "बोलकर बताएं",
  "Add screenshot": "स्क्रीनशॉट जोड़ें",
  "Remove": "हटाएं",
  "Check this for me": "इसे मेरे लिए जांचें",
  "Checking this...": "जांच हो रही है...",
  "There is a problem": "एक समस्या है",
  "Not sure what to paste? Try one:": "पेस्ट करने में असमंजस है? इनमें से एक आज़माएं:",
  "A suspicious link": "एक संदिग्ध लिंक",
  "A strange UPI ID": "एक अजीब UPI ID",
  "A scam message": "एक ठगी वाला मैसेज",
  "Raksha will never ask for your OTP, PIN, card number, or password.": "रक्षा आपसे OTP, PIN, कार्ड नंबर या पासवर्ड कभी नहीं मांगेगा।",
  // Private photo protection
  "Is someone threatening to share your photos?": "क्या कोई आपकी तस्वीरें साझा करने की धमकी दे रहा है?",
  "You can act on it here without showing the photo to anyone, including us.": "आप यहां कार्रवाई कर सकते हैं, किसी को भी तस्वीर दिखाए बिना — हमें भी नहीं।",
  "Do NOT send, share, or download any photo or video in order to use this.": "इसका उपयोग करने के लिए कोई फ़ोटो या वीडियो भेजें, साझा करें या डाउनलोड न करें।",
  "Only use a photo that is already on this device.": "केवल वही फ़ोटो चुनें जो पहले से इस डिवाइस पर है।",
  "Choose the photo to protect": "सुरक्षित करने के लिए फ़ोटो चुनें",
  "A photo will not be shown on this screen": "इस स्क्रीन पर फ़ोटो नहीं दिखाई जाएगी",
  "Your photo will not leave this device. Only a code made from it is sent, never the photo itself.": "आपकी फ़ोटो इस डिवाइस से बाहर नहीं जाएगी। उससे बना केवल एक कोड भेजा जाता है, फ़ोटो कभी नहीं।",
  "You do not have to give your name to use this.": "इसका उपयोग करने के लिए अपना नाम देना ज़रूरी नहीं है।",
  "Kept on this device. Not shown, not uploaded.": "इस डिवाइस पर ही रखा गया। न दिखाया, न अपलोड किया।",
  "Your photo is protected.": "आपकी फ़ोटो सुरक्षित है।",
  "Open my case": "मेरा केस खोलें",
  "Copy code": "कोड कॉपी करें",
  // Verdict screen
  "What we found": "हमें यह मिला",
  "Check something else": "कुछ और जांचें",
  "Needs caution": "सावधानी चाहिए",
  "No match found": "कोई मिलान नहीं मिला",
  "This is not your fault.": "यह आपकी गलती नहीं है।",
  "Do this now": "अभी यह करें",
  "Has any of this already happened?": "क्या इनमें से कुछ पहले ही हो चुका है?",
  "Money was sent": "पैसा भेजा गया",
  "I shared an OTP, PIN, or password": "मैंने OTP, PIN या पासवर्ड साझा किया",
  "I installed an app or shared my screen": "मैंने ऐप इंस्टॉल किया या स्क्रीन साझा की",
  "Private photos or videos are involved": "निजी फ़ोटो या वीडियो शामिल हैं",
  "None of this has happened yet": "इनमें से कुछ भी अभी नहीं हुआ",
  "Why we flagged this": "हमने इसे क्यों चिह्नित किया",
  "What we cannot tell you": "हम आपको क्या नहीं बता सकते",
  "What they will try next": "वे आगे क्या करेंगे",
  "Do not do this": "यह न करें",
  "Have we understood this correctly?": "क्या हमने इसे सही समझा?",
  "Nothing has been sent yet.": "अभी कुछ भी नहीं भेजा गया है।",
  "Continue to your report": "अपनी रिपोर्ट पर जारी रखें",
  "Back to response desk": "रिस्पॉन्स डेस्क पर वापस",
  "Back to action board": "एक्शन बोर्ड पर वापस",
  "Back to recovery cockpit": "रिकवरी कॉकपिट पर वापस",
  "Quick Exit": "त्वरित बाहर निकलें",
  "Triage": "प्राथमिक जाँच",
  "Tell the story": "घटना बताएं",
  "Confirm facts": "तथ्यों की पुष्टि",
  "Act and track": "कार्रवाई और ट्रैकिंग",
  "Step 01 / incident intake": "चरण 01 / घटना इनटेक",
  "Show us what happened.": "बताइए क्या हुआ।",
  "We will identify the script, explain what may happen next, and prepare the safest response path.": "हम ठगी का तरीका पहचानेंगे, आगे क्या हो सकता है समझाएंगे, और सबसे सुरक्षित प्रतिक्रिया पथ तैयार करेंगे।",
  "If money is leaving now, call 1930 before you finish this form.": "अगर अभी पैसा जा रहा है, तो फॉर्म पूरा करने से पहले 1930 पर कॉल करें।",
  "Start with the incident record. We will keep the recovery actions in view.": "घटना रिकॉर्ड से शुरू करें। रिकवरी कार्रवाईयां हम सामने रखेंगे।",
  "This environment does not transmit reports to authorities.": "यह वातावरण अधिकारियों को रिपोर्ट नहीं भेजता है।",
  "Message": "मैसेज",
  "Voice": "आवाज़",
  "Screenshot": "स्क्रीनशॉट",
  "Number or link": "नंबर या लिंक",
  "Private image hash": "निजी छवि फ़िंगरप्रिंट",
  "Paste the message or conversation": "मैसेज या बातचीत पेस्ट करें",
  "English, Hindi, and Hinglish input are accepted. Avoid entering real personal information in this environment.": "अंग्रेज़ी, हिंदी और हिंग्लिश इनपुट स्वीकार किए जाते हैं। इस वातावरण में असली निजी जानकारी न डालें।",
  "Tell the story in your own words": "अपने शब्दों में घटना बताएं",
  "Use the browser microphone for a local transcript. Hinglish works best when you choose the language you naturally speak.": "लोकल ट्रांसक्रिप्ट के लिए ब्राउज़र माइक्रोफ़ोन का उपयोग करें। जिस भाषा में आप स्वाभाविक रूप से बोलते हैं उसे चुनें।",
  "Voice language": "आवाज़ की भाषा",
  "Start recording": "रिकॉर्डिंग शुरू करें",
  "Stop recording": "रिकॉर्डिंग रोकें",
  "Transcript": "ट्रांसक्रिप्ट",
  "Drop an image here or browse": "यहां छवि छोड़ें या ब्राउज़ करें",
  "Remove image": "छवि हटाएं",
  "Local fingerprinting": "लोकल फ़िंगरप्रिंटिंग",
  "Enter a phone number, UPI ID, or link": "फ़ोन नंबर, UPI ID या लिंक डालें",
  "Identifiers are analysed as incident evidence. Never enter real account numbers or OTPs.": "पहचानकर्ताओं का घटना साक्ष्य के रूप में विश्लेषण होता है। असली खाता नंबर या OTP कभी न डालें।",
  "Analyse this incident": "इस घटना का विश्लेषण करें",
  "Create local fingerprint": "लोकल फ़िंगरप्रिंट बनाएं",
  "Want to see the complete response path?": "पूरा प्रतिक्रिया पथ देखना चाहते हैं?",
  "Open the example task-scam case": "उदाहरण टास्क-स्कैम केस खोलें",
  "Money moving now?": "अभी पैसा जा रहा है?",
  "Call 1930 immediately. This intake can wait.": "तुरंत 1930 पर कॉल करें। यह फॉर्म बाद में भी हो सकता है।",
  "Call 1930": "1930 पर कॉल करें",
  "Privacy boundary": "गोपनीयता सीमा",
  "Text is redacted before model analysis. Uploaded screenshots are temporary analysis inputs. Private-image fingerprints stay local.": "मॉडल विश्लेषण से पहले टेक्स्ट संपादित किया जाता है। अपलोड किए गए स्क्रीनशॉट अस्थायी विश्लेषण इनपुट हैं। निजी छवि फ़िंगरप्रिंट डिवाइस पर ही रहते हैं।",
  "Case tracking": "केस ट्रैकिंग",
  "Find your recovery plan.": "अपना रिकवरी प्लान खोजें।",
  "Enter the acknowledgement number from your case record. An example case is available without an account.": "अपने केस रिकॉर्ड का पावती नंबर डालें। बिना खाते के एक उदाहरण केस उपलब्ध है।",
  "Acknowledgement number": "पावती नंबर",
  "Open case": "केस खोलें",
  "Open an example case": "उदाहरण केस खोलें",
  "See clocks, packet statuses, routing events, and the recovery warning in the complete journey.": "पूरी प्रक्रिया में समय-सीमाएं, पैकेट स्टेटस, रूटिंग इवेंट्स और रिकवरी चेतावनी देखें।",
  "Threat bulletin / pattern corpus": "खतरा बुलेटिन / पैटर्न कोष",
  "Active scam scripts in the atlas.": "एटलस में सक्रिय ठगी के तरीके।",
  "These are behavioural playbooks sourced from public advisories and represented with anonymised examples. A pattern match is a warning, not a finding of guilt.": "ये सार्वजनिक परामर्शों से लिए गए व्यवहारिक तरीके हैं, जिन्हें गुमनाम उदाहरणों से दिखाया गया है। पैटर्न मैच एक चेतावनी है, दोष का प्रमाण नहीं।",
  "High risk": "उच्च जोखिम",
  "Read playbook": "तरीका पढ़ें",
  "This is what the evidence suggests.": "साक्ष्य से यह संकेत मिलता है।",
  "Confirm extracted facts": "निकाले गए तथ्यों की पुष्टि करें",
  "Act in the right order.": "सही क्रम में कार्रवाई करें।",
  "Review the incident before routing.": "रूटिंग से पहले घटना की समीक्षा करें।",
  "Advisory result": "परामर्शी परिणाम",
  "Recovery cockpit": "रिकवरी कॉकपिट",
  "Recovery scam warning": "रिकवरी स्कैम चेतावनी",
  "A filed report can attract a second scam.": "दर्ज रिपोर्ट दूसरी ठगी को आकर्षित कर सकती है।",
  "No police officer, CBI official, bank representative, or I4C representative should ask for money to release your funds.": "कोई भी पुलिस अधिकारी, CBI अधिकारी, बैंक प्रतिनिधि या I4C प्रतिनिधि आपका पैसा छुड़ाने के लिए पैसे नहीं मांगेगा।",
  "Case state": "केस स्थिति",
  "packets prepared": "पैकेट तैयार",
  "facts still open": "तथ्य अभी बाकी",
  "Call 1930 now": "अभी 1930 पर कॉल करें",
  "Prepare response packets": "रिस्पॉन्स पैकेट तैयार करें",
  "Read threat bulletin": "खतरा बुलेटिन पढ़ें",
  "Financial amount": "वित्तीय राशि",
  "Bank or wallet": "बैंक या वॉलेट",
  "Incident description": "घटना का विवरण",
  "This prepares recipient-specific records. Nothing is transmitted to an institution from this environment.": "यह प्राप्तकर्ता-विशिष्ट रिकॉर्ड तैयार करता है। इस वातावरण से किसी संस्था को कुछ नहीं भेजा जाता।",
  "Operator console / case record": "ऑपरेटर कंसोल / केस रिकॉर्ड",
  "See the incident graph behind the journey.": "प्रक्रिया के पीछे का घटना ग्राफ देखें।",
  "Freeze through your bank": "अपने बैंक से फ्रीज़ कराएं",
  "Preserve evidence before deleting anything.": "कुछ भी हटाने से पहले साक्ष्य सुरक्षित करें।",
  "New incident": "नई घटना",
};

const TAMIL: Record<string, string> = {
  // Intake (smart input)
  "Step 01 / tell us what happened": "படி 01 / என்ன நடந்தது சொல்லுங்கள்",
  "Paste anything you received. We work out what it is and check it for you.": "உங்களுக்கு வந்ததை ஒட்டுங்கள். அது என்ன என்பதை நாங்கள் கண்டறிந்து உங்களுக்காக சரிபார்ப்போம்.",
  "Take as long as you need. Nothing is checked until you choose to continue, and you can ask someone you trust to help you with this.": "உங்களுக்கு தேவையான நேரம் எடுத்துக்கொள்ளுங்கள். நீங்கள் தொடர முடிவு செய்யும் வரை எதுவும் சரிபார்க்கப்படாது. நம்பிக்கையான ஒருவரின் உதவியையும் நாடலாம்.",
  "See a worked example": "ஒரு உதாரணத்தைப் பாருங்கள்",
  "What did they send you?": "அவர்கள் உங்களுக்கு என்ன அனுப்பினார்கள்?",
  "A message, a phone number, a UPI ID, or a link. One box takes all of them.": "செய்தி, தொலைபேசி எண், UPI ID அல்லது இணைப்பு. ஒரே பெட்டியில் அனைத்தும்.",
  "Speak instead": "பேசிச் சொல்லுங்கள்",
  "Add screenshot": "திரைப்படம் சேர்க்க",
  "Remove": "நீக்கு",
  "Check this for me": "இதை எனக்காக சரிபார்",
  "Checking this...": "சரிபார்க்கிறோம்...",
  "There is a problem": "ஒரு சிக்கல் உள்ளது",
  "Not sure what to paste? Try one:": "எதை ஒட்டுவது எனத் தெரியவில்லையா? ஒன்றை முயற்சிக்கவும்:",
  "A suspicious link": "சந்தேகத்திற்குரிய இணைப்பு",
  "A strange UPI ID": "வித்தியாசமான UPI ID",
  "A scam message": "மோசடி செய்தி",
  "Raksha will never ask for your OTP, PIN, card number, or password.": "ரக்ஷா உங்கள் OTP, PIN, அட்டை எண் அல்லது கடவுச்சொல்லை எப்போதும் கேட்காது.",
  // Private photo protection
  "Is someone threatening to share your photos?": "உங்கள் படங்களைப் பங்கிடுவேன் என யாரோ மிரட்டுகிறாரா?",
  "You can act on it here without showing the photo to anyone, including us.": "படத்தை யாருக்கும் — எங்களுக்கும் — காட்டாமல் இங்கே நடவடிக்கை எடுக்கலாம்.",
  "Do NOT send, share, or download any photo or video in order to use this.": "இதைப் பயன்படுத்த எந்தப் படத்தையும் வீடியோவையும் அனுப்ப, பங்கிட, பதிவிறக்க வேண்டாம்.",
  "Only use a photo that is already on this device.": "இந்தச் சாதனத்தில் ஏற்கெனவே உள்ள படத்தை மட்டும் பயன்படுத்துங்கள்.",
  "Choose the photo to protect": "பாதுகாக்க வேண்டிய படத்தைத் தேர்ந்தெடுங்கள்",
  "A photo will not be shown on this screen": "இந்தத் திரையில் படம் காட்டப்படாது",
  "Your photo will not leave this device. Only a code made from it is sent, never the photo itself.": "உங்கள் படம் இந்தச் சாதனத்தை விட்டு வெளியேறாது. அதிலிருந்து உருவான குறியீடு மட்டுமே அனுப்பப்படும், படம் அல்ல.",
  "You do not have to give your name to use this.": "இதைப் பயன்படுத்த உங்கள் பெயரைத் தர வேண்டியதில்லை.",
  "Kept on this device. Not shown, not uploaded.": "இந்தச் சாதனத்தில் மட்டும். காட்டப்படவில்லை, பதிவேற்றப்படவில்லை.",
  "Your photo is protected.": "உங்கள் படம் பாதுகாக்கப்பட்டுள்ளது.",
  "Open my case": "எனது வழக்கைத் திற",
  "Copy code": "குறியீட்டை நகலெடு",
  // Verdict screen
  "What we found": "நாங்கள் கண்டறிந்தது",
  "Check something else": "வேறு ஒன்றைச் சரிபார்",
  "Needs caution": "எச்சரிக்கை தேவை",
  "No match found": "பொருத்தம் கிடைக்கவில்லை",
  "This is not your fault.": "இது உங்கள் தவறு அல்ல.",
  "Do this now": "இதை இப்போதே செய்யுங்கள்",
  "Has any of this already happened?": "இவற்றில் ஏதேனும் ஏற்கெனவே நடந்துவிட்டதா?",
  "Money was sent": "பணம் அனுப்பப்பட்டது",
  "I shared an OTP, PIN, or password": "நான் OTP, PIN அல்லது கடவுச்சொல்லைப் பங்கிட்டேன்",
  "I installed an app or shared my screen": "நான் ஆப்ஸ் நிறுவினேன் அல்லது திரையைப் பங்கிட்டேன்",
  "Private photos or videos are involved": "தனிப்பட்ட படங்கள் அல்லது வீடியோக்கள் தொடர்புடையவை",
  "None of this has happened yet": "இவற்றில் எதுவும் இன்னும் நடக்கவில்லை",
  "Why we flagged this": "இதை நாங்கள் ஏன் குறித்தோம்",
  "What we cannot tell you": "எங்களால் சொல்ல முடியாதவை",
  "What they will try next": "அவர்கள் அடுத்து என்ன செய்வார்கள்",
  "Do not do this": "இதைச் செய்ய வேண்டாம்",
  "Have we understood this correctly?": "நாங்கள் இதைச் சரியாகப் புரிந்துகொண்டோமா?",
  "Nothing has been sent yet.": "இன்னும் எதுவும் அனுப்பப்படவில்லை.",
  "Continue to your report": "உங்கள் அறிக்கைக்குத் தொடரவும்",
  "Back to response desk": "பதில் மையத்திற்குத் திரும்பு",
  "Back to action board": "நடவடிக்கை பலகைக்குத் திரும்பு",
  "Back to recovery cockpit": "மீட்பு மையத்திற்குத் திரும்பு",
  "Triage": "முதல் பிரிப்பு",
  "Tell the story": "சம்பவத்தைச் சொல்லுங்கள்",
  "Confirm facts": "உண்மைகளை உறுதி செய்யுங்கள்",
  "Act and track": "செயல்படுத்தி கண்காணியுங்கள்",
  "Step 01 / incident intake": "படி 01 / சம்பவ பதிவு",
  "Show us what happened.": "என்ன நடந்தது என்பதைக் காட்டுங்கள்.",
  "We will identify the script, explain what may happen next, and prepare the safest response path.": "மோசடி முறையைக் கண்டறிந்து, அடுத்து என்ன நடக்கும் என விளக்கி, பாதுகாப்பான பதில் பாதையைத் தயாரிப்போம்.",
  "If money is leaving now, call 1930 before you finish this form.": "இப்போது பணம் சென்றால், இந்தப் படிவத்தை முடிக்கும் முன் 1930-ஐ அழைக்கவும்.",
  "Start with the incident record. We will keep the recovery actions in view.": "சம்பவ பதிவில் தொடங்குங்கள். மீட்பு நடவடிக்கைகளைக் கண்முன் வைத்திருப்போம்.",
  "This environment does not transmit reports to authorities.": "இந்த சூழல் அதிகாரிகளுக்குப் புகார்களை அனுப்பாது.",
  "Message": "செய்தி",
  "Voice": "குரல்",
  "Screenshot": "திரைக்காட்சி",
  "Number or link": "எண் அல்லது இணைப்பு",
  "Private image hash": "தனியார் பட குறிப்பு",
  "Paste the message or conversation": "செய்தி அல்லது உரையாடலை ஒட்டவும்",
  "Tell the story in your own words": "உங்கள் சொந்த வார்த்தைகளில் சொல்லுங்கள்",
  "Voice language": "குரல் மொழி",
  "Start recording": "பதிவைத் தொடங்கு",
  "Stop recording": "பதிவை நிறுத்து",
  "Transcript": "உரைநகல்",
  "Drop an image here or browse": "இங்கே படத்தை இடவும் அல்லது உலாவவும்",
  "Remove image": "படத்தை அகற்று",
  "Local fingerprinting": "உள்ளக குறிப்புருவம்",
  "Enter a phone number, UPI ID, or link": "தொலைபேசி எண், UPI ID அல்லது இணைப்பை உள்ளிடவும்",
  "Identifiers are analysed as incident evidence. Never enter real account numbers or OTPs.": "அடையாளங்கள் சம்பவ ஆதாரமாக பகுப்பாய்வு செய்யப்படுகின்றன. உண்மையான கணக்கு எண்கள் அல்லது OTP-களை உள்ளிட வேண்டாம்.",
  "Analyse this incident": "இந்த சம்பவத்தை பகுப்பாய்வு செய்",
  "Create local fingerprint": "உள்ளக குறிப்புருவம் உருவாக்கு",
  "Want to see the complete response path?": "முழு பதில் பாதையைக் காண விரும்புகிறீர்களா?",
  "Open the example task-scam case": "எடுத்துக்காட்டு டாஸ்க்-ஸ்கேம் வழக்கைத் திற",
  "Money moving now?": "இப்போது பணம் செல்கிறதா?",
  "Call 1930 immediately. This intake can wait.": "உடனே 1930-ஐ அழைக்கவும். இந்தப் பதிவு காத்திருக்கும்.",
  "Call 1930": "1930-ஐ அழை",
  "Privacy boundary": "தனியுரிமை எல்லை",
  "Text is redacted before model analysis. Uploaded screenshots are temporary analysis inputs. Private-image fingerprints stay local.": "மாடல் பகுப்பாய்வுக்கு முன் உரை திருத்தப்படுகிறது. பதிவேற்றிய திரைக்காட்சிகள் தற்காலிக பகுப்பாய்வு உள்ளீடுகள். தனிப்பட்ட பட குறிப்புகள் சாதனத்திலேயே இருக்கும்.",
  "English, Hindi, and Hinglish input are accepted. Avoid entering real personal information in this environment.": "தமிழ் உட்பட பல மொழி உள்ளீடுகள் ஏற்கப்படுகின்றன. இந்த சூழலில் உண்மையான தனிப்பட்ட தகவல்களை உள்ளிட வேண்டாம்.",
  "Case tracking": "வழக்கு கண்காணிப்பு",
  "Find your recovery plan.": "உங்கள் மீட்பு திட்டத்தைக் கண்டறியவும்.",
  "Enter the acknowledgement number from your case record. An example case is available without an account.": "உங்கள் வழக்கு பதிவின் அங்கீகார எண்ணை உள்ளிடவும். கணக்கு இல்லாமல் ஒரு எடுத்துக்காட்டு வழக்கு கிடைக்கும்.",
  "Acknowledgement number": "அங்கீகார எண்",
  "Open case": "வழக்கைத் திற",
  "Open an example case": "எடுத்துக்காட்டு வழக்கைத் திற",
  "Threat bulletin / pattern corpus": "அச்சுறுத்தல் அறிவிப்பு / முறை தொகுப்பு",
  "Active scam scripts in the atlas.": "அட்லஸில் உள்ள நடப்பு மோசடி முறைகள்.",
  "High risk": "அதிக ஆபத்து",
  "Read playbook": "முறையைப் படி",
  "This is what the evidence suggests.": "ஆதாரம் இதையே காட்டுகிறது.",
  "Confirm extracted facts": "பிரித்தெடுக்கப்பட்ட உண்மைகளை உறுதி செய்யவும்",
  "Act in the right order.": "சரியான வரிசையில் செயல்படுங்கள்.",
  "Review the incident before routing.": "அனுப்பும் முன் சம்பவத்தை மதிப்பாய்வு செய்யுங்கள்.",
  "Advisory result": "ஆலோசனை முடிவு",
  "Recovery cockpit": "மீட்பு மையம்",
  "Recovery scam warning": "மீட்பு மோசடி எச்சரிக்கை",
  "A filed report can attract a second scam.": "பதிவு செய்யப்பட்ட புகார் இரண்டாவது மோசடியை ஈர்க்கலாம்.",
  "No police officer, CBI official, bank representative, or I4C representative should ask for money to release your funds.": "உங்கள் பணத்தை விடுவிக்க எந்த காவலர், CBI அதிகாரி, வங்கி பிரதிநிதி அல்லது I4C பிரதிநிதியும் பணம் கேட்க மாட்டார்கள்.",
  "Case state": "வழக்கு நிலை",
  "packets prepared": "தொகுப்புகள் தயார்",
  "facts still open": "உண்மைகள் நிலுவையில்",
  "Call 1930 now": "இப்போதே 1930-ஐ அழை",
  "Prepare response packets": "பதில் தொகுப்புகளைத் தயாரி",
  "Financial amount": "நிதி தொகை",
  "Bank or wallet": "வங்கி அல்லது வாலட்",
  "Incident description": "சம்பவ விவரம்",
  "Freeze through your bank": "உங்கள் வங்கி மூலம் முடக்கவும்",
  "Preserve evidence before deleting anything.": "எதையும் நீக்கும் முன் ஆதாரத்தைப் பாதுகாக்கவும்.",
  "New incident": "புதிய சம்பவம்",
};

const TELUGU: Record<string, string> = {
  // Intake (smart input)
  "Step 01 / tell us what happened": "దశ 01 / ఏం జరిగిందో చెప్పండి",
  "Paste anything you received. We work out what it is and check it for you.": "మీకు వచ్చినది ఇక్కడ పేస్ట్ చేయండి. అది ఏమిటో మేము గుర్తించి మీ కోసం తనిఖీ చేస్తాము.",
  "Take as long as you need. Nothing is checked until you choose to continue, and you can ask someone you trust to help you with this.": "మీకు కావలసినంత సమయం తీసుకోండి. మీరు కొనసాగించాలని ఎంచుకునే వరకు ఏదీ తనిఖీ చేయబడదు. నమ్మకమైన వ్యక్తి సహాయం కూడా అడగవచ్చు.",
  "See a worked example": "ఒక ఉదాహరణ చూడండి",
  "What did they send you?": "వారు మీకు ఏమి పంపారు?",
  "A message, a phone number, a UPI ID, or a link. One box takes all of them.": "సందేశం, ఫోన్ నంబర్, UPI ID లేదా లింక్. ఒకే బాక్స్‌లో అన్నీ.",
  "Speak instead": "మాట్లాడి చెప్పండి",
  "Add screenshot": "స్క్రీన్‌షాట్ జోడించండి",
  "Remove": "తీసివేయండి",
  "Check this for me": "ఇది నా కోసం తనిఖీ చేయండి",
  "Checking this...": "తనిఖీ చేస్తున్నాము...",
  "There is a problem": "ఒక సమస్య ఉంది",
  "Not sure what to paste? Try one:": "ఏమి పేస్ట్ చేయాలో తెలియదా? ఒకటి ప్రయత్నించండి:",
  "A suspicious link": "అనుమానాస్పద లింక్",
  "A strange UPI ID": "వింత UPI ID",
  "A scam message": "మోసపూరిత సందేశం",
  "Raksha will never ask for your OTP, PIN, card number, or password.": "రక్ష మీ OTP, PIN, కార్డ్ నంబర్ లేదా పాస్‌వర్డ్ ఎప్పుడూ అడగదు.",
  // Private photo protection
  "Is someone threatening to share your photos?": "మీ ఫోటోలను షేర్ చేస్తానని ఎవరైనా బెదిరిస్తున్నారా?",
  "You can act on it here without showing the photo to anyone, including us.": "ఫోటోను ఎవరికీ — మాకు కూడా — చూపకుండా ఇక్కడ చర్య తీసుకోవచ్చు.",
  "Do NOT send, share, or download any photo or video in order to use this.": "ఇది ఉపయోగించడానికి ఏ ఫోటో లేదా వీడియోను పంపవద్దు, షేర్ చేయవద్దు, డౌన్‌లోడ్ చేయవద్దు.",
  "Only use a photo that is already on this device.": "ఈ పరికరంలో ఇప్పటికే ఉన్న ఫోటోను మాత్రమే ఉపయోగించండి.",
  "Choose the photo to protect": "రక్షించాల్సిన ఫోటోను ఎంచుకోండి",
  "A photo will not be shown on this screen": "ఈ స్క్రీన్‌పై ఫోటో చూపబడదు",
  "Your photo will not leave this device. Only a code made from it is sent, never the photo itself.": "మీ ఫోటో ఈ పరికరాన్ని విడిచిపెట్టదు. దాని నుండి తయారైన కోడ్ మాత్రమే పంపబడుతుంది, ఫోటో ఎప్పుడూ కాదు.",
  "You do not have to give your name to use this.": "ఇది ఉపయోగించడానికి మీ పేరు ఇవ్వాల్సిన అవసరం లేదు.",
  "Kept on this device. Not shown, not uploaded.": "ఈ పరికరంలోనే ఉంచబడింది. చూపలేదు, అప్‌లోడ్ చేయలేదు.",
  "Your photo is protected.": "మీ ఫోటో రక్షించబడింది.",
  "Open my case": "నా కేసు తెరవండి",
  "Copy code": "కోడ్ కాపీ చేయండి",
  // Verdict screen
  "What we found": "మేము కనుగొన్నది",
  "Check something else": "మరొకటి తనిఖీ చేయండి",
  "Needs caution": "జాగ్రత్త అవసరం",
  "No match found": "సరిపోలిక కనుగొనబడలేదు",
  "This is not your fault.": "ఇది మీ తప్పు కాదు.",
  "Do this now": "ఇది ఇప్పుడే చేయండి",
  "Has any of this already happened?": "వీటిలో ఏదైనా ఇప్పటికే జరిగిందా?",
  "Money was sent": "డబ్బు పంపబడింది",
  "I shared an OTP, PIN, or password": "నేను OTP, PIN లేదా పాస్‌వర్డ్ షేర్ చేశాను",
  "I installed an app or shared my screen": "నేను యాప్ ఇన్‌స్టాల్ చేశాను లేదా స్క్రీన్ షేర్ చేశాను",
  "Private photos or videos are involved": "వ్యక్తిగత ఫోటోలు లేదా వీడియోలు ఉన్నాయి",
  "None of this has happened yet": "వీటిలో ఏదీ ఇంకా జరగలేదు",
  "Why we flagged this": "మేము ఇది ఎందుకు గుర్తించాము",
  "What we cannot tell you": "మేము మీకు చెప్పలేనివి",
  "What they will try next": "వారు తర్వాత ఏమి చేస్తారు",
  "Do not do this": "ఇది చేయవద్దు",
  "Have we understood this correctly?": "మేము దీనిని సరిగ్గా అర్థం చేసుకున్నామా?",
  "Nothing has been sent yet.": "ఇంకా ఏదీ పంపబడలేదు.",
  "Continue to your report": "మీ నివేదికకు కొనసాగండి",
  "Back to response desk": "ప్రతిస్పందన డెస్క్‌కు తిరిగి",
  "Back to action board": "యాక్షన్ బోర్డ్‌కు తిరిగి",
  "Back to recovery cockpit": "రికవరీ కాక్‌పిట్‌కు తిరిగి",
  "Triage": "ప్రాథమిక విభజన",
  "Tell the story": "సంఘటనను చెప్పండి",
  "Confirm facts": "వాస్తవాలను నిర్ధారించండి",
  "Act and track": "చర్య మరియు ట్రాకింగ్",
  "Step 01 / incident intake": "దశ 01 / సంఘటన ఇన్‌టేక్",
  "Show us what happened.": "ఏమి జరిగిందో చెప్పండి.",
  "We will identify the script, explain what may happen next, and prepare the safest response path.": "మేము మోసపు పద్ధతిని గుర్తించి, తర్వాత ఏమి జరగొచ్చో వివరించి, సురక్షితమైన ప్రతిస్పందన మార్గాన్ని సిద్ధం చేస్తాము.",
  "If money is leaving now, call 1930 before you finish this form.": "ఇప్పుడు డబ్బు వెళ్తుంటే, ఈ ఫారం పూర్తి చేయకముందే 1930కి కాల్ చేయండి.",
  "Start with the incident record. We will keep the recovery actions in view.": "సంఘటన రికార్డుతో ప్రారంభించండి. రికవరీ చర్యలను మేము ముందుంచుతాము.",
  "This environment does not transmit reports to authorities.": "ఈ వాతావరణం అధికారులకు నివేదికలను పంపదు.",
  "Message": "మెసేజ్",
  "Voice": "వాయిస్",
  "Screenshot": "స్క్రీన్‌షాట్",
  "Number or link": "నంబర్ లేదా లింక్",
  "Private image hash": "ప్రైవేట్ ఇమేజ్ ఫింగర్‌ప్రింట్",
  "Paste the message or conversation": "మెసేజ్ లేదా సంభాషణను పేస్ట్ చేయండి",
  "Tell the story in your own words": "మీ స్వంత మాటల్లో సంఘటనను చెప్పండి",
  "Voice language": "వాయిస్ భాష",
  "Start recording": "రికార్డింగ్ ప్రారంభించండి",
  "Stop recording": "రికార్డింగ్ ఆపండి",
  "Transcript": "ట్రాన్స్‌క్రిప్ట్",
  "Drop an image here or browse": "ఇక్కడ చిత్రాన్ని వదలండి లేదా బ్రౌజ్ చేయండి",
  "Remove image": "చిత్రాన్ని తొలగించండి",
  "Local fingerprinting": "స్థానిక ఫింగర్‌ప్రింటింగ్",
  "Enter a phone number, UPI ID, or link": "ఫోన్ నంబర్, UPI ID లేదా లింక్ నమోదు చేయండి",
  "Identifiers are analysed as incident evidence. Never enter real account numbers or OTPs.": "గుర్తింపులు సంఘటన సాక్ష్యంగా విశ్లేషించబడతాయి. నిజమైన ఖాతా నంబర్లు లేదా OTPలు ఎప్పుడూ నమోదు చేయకండి.",
  "Analyse this incident": "ఈ సంఘటనను విశ్లేషించండి",
  "Create local fingerprint": "స్థానిక ఫింగర్‌ప్రింట్ సృష్టించండి",
  "Want to see the complete response path?": "పూర్తి ప్రతిస్పందన మార్గాన్ని చూడాలనుకుంటున్నారా?",
  "Open the example task-scam case": "ఉదాహరణ టాస్క్-స్కామ్ కేసును తెరవండి",
  "Money moving now?": "ఇప్పుడు డబ్బు వెళ్తోందా?",
  "Call 1930 immediately. This intake can wait.": "వెంటనే 1930కి కాల్ చేయండి. ఈ ఇన్‌టేక్ వేచి ఉంటుంది.",
  "Call 1930": "1930కి కాల్ చేయండి",
  "Privacy boundary": "గోప్యతా సరిహద్దు",
  "Text is redacted before model analysis. Uploaded screenshots are temporary analysis inputs. Private-image fingerprints stay local.": "మోడల్ విశ్లేషణకు ముందు టెక్స్ట్ సవరించబడుతుంది. అప్‌లోడ్ చేసిన స్క్రీన్‌షాట్‌లు తాత్కాలిక విశ్లేషణ ఇన్‌పుట్‌లు. ప్రైవేట్ చిత్రాల ఫింగర్‌ప్రింట్లు పరికరంలోనే ఉంటాయి.",
  "English, Hindi, and Hinglish input are accepted. Avoid entering real personal information in this environment.": "తెలుగుతో సహా అనేక భాషల ఇన్‌పుట్ అంగీకరించబడుతుంది. ఈ వాతావరణంలో నిజమైన వ్యక్తిగత సమాచారం నమోదు చేయవద్దు.",
  "Case tracking": "కేసు ట్రాకింగ్",
  "Find your recovery plan.": "మీ రికవరీ ప్రణాళికను కనుగొనండి.",
  "Enter the acknowledgement number from your case record. An example case is available without an account.": "మీ కేసు రికార్డులోని రసీదు నంబరును నమోదు చేయండి. ఖాతా లేకుండా ఒక ఉదాహరణ కేసు అందుబాటులో ఉంది.",
  "Acknowledgement number": "రసీదు నంబరు",
  "Open case": "కేసు తెరవండి",
  "Open an example case": "ఉదాహరణ కేసు తెరవండి",
  "Threat bulletin / pattern corpus": "ముప్పు బులెటిన్ / పద్ధతుల సంగ్రహం",
  "Active scam scripts in the atlas.": "అట్లాస్‌లో క్రియాశీల స్కామ్ పద్ధతులు.",
  "High risk": "అధిక ప్రమాదం",
  "Read playbook": "పద్ధతిని చదవండి",
  "This is what the evidence suggests.": "సాక్ష్యం ఇదే సూచిస్తుంది.",
  "Confirm extracted facts": "సేకరించిన వాస్తవాలను నిర్ధారించండి",
  "Act in the right order.": "సరైన క్రమంలో చర్య తీసుకోండి.",
  "Review the incident before routing.": "రూటింగ్ ముందు సంఘటనను సమీక్షించండి.",
  "Advisory result": "సలహా ఫలితం",
  "Recovery cockpit": "రికవరీ కాక్‌పిట్",
  "Recovery scam warning": "రికవరీ స్కామ్ హెచ్చరిక",
  "A filed report can attract a second scam.": "నమోదైన ఫిర్యాదు రెండో స్కామ్‌ను ఆకర్షించవచ్చు.",
  "No police officer, CBI official, bank representative, or I4C representative should ask for money to release your funds.": "మీ నిధులను విడుదల చేయడానికి ఎటువంటి పోలీసు అధికారి, CBI అధికారి, బ్యాంకు ప్రతినిధి లేదా I4C ప్రతినిధి డబ్బు అడగరాదు.",
  "Case state": "కేసు స్థితి",
  "packets prepared": "ప్యాకెట్లు సిద్ధం",
  "facts still open": "వాస్తవాలు ఇంకా బాకీ",
  "Call 1930 now": "ఇప్పుడే 1930కి కాల్ చేయండి",
  "Prepare response packets": "ప్రతిస్పందన ప్యాకెట్లను సిద్ధం చేయండి",
  "Financial amount": "ఆర్థిక మొత్తం",
  "Bank or wallet": "బ్యాంకు లేదా వాలెట్",
  "Incident description": "సంఘటన వివరణ",
  "Freeze through your bank": "మీ బ్యాంకు ద్వారా ఫ్రీజ్ చేయించండి",
  "Preserve evidence before deleting anything.": "ఏదైనా తొలగించే ముందు సాక్ష్యాన్ని భద్రపరచండి.",
  "New incident": "కొత్త సంఘటన",
};

const BENGALI: Record<string, string> = {
  // Intake (smart input)
  "Step 01 / tell us what happened": "ধাপ 01 / কী হয়েছে বলুন",
  "Paste anything you received. We work out what it is and check it for you.": "আপনি যা পেয়েছেন তা পেস্ট করুন। এটি কী তা আমরা বুঝে আপনার জন্য যাচাই করব।",
  "Take as long as you need. Nothing is checked until you choose to continue, and you can ask someone you trust to help you with this.": "যত সময় দরকার নিন। আপনি এগিয়ে যেতে না চাইলে কিছুই যাচাই করা হয় না। বিশ্বস্ত কারও সাহায্যও নিতে পারেন।",
  "See a worked example": "একটি উদাহরণ দেখুন",
  "What did they send you?": "তারা আপনাকে কী পাঠিয়েছে?",
  "A message, a phone number, a UPI ID, or a link. One box takes all of them.": "মেসেজ, ফোন নম্বর, UPI ID বা লিঙ্ক। একটি বাক্সেই সব চলবে।",
  "Speak instead": "বলে জানান",
  "Add screenshot": "স্ক্রিনশট যোগ করুন",
  "Remove": "সরান",
  "Check this for me": "এটি আমার জন্য যাচাই করুন",
  "Checking this...": "যাচাই করা হচ্ছে...",
  "There is a problem": "একটি সমস্যা আছে",
  "Not sure what to paste? Try one:": "কী পেস্ট করবেন বুঝতে পারছেন না? একটি চেষ্টা করুন:",
  "A suspicious link": "একটি সন্দেহজনক লিঙ্ক",
  "A strange UPI ID": "একটি অস্বাভাবিক UPI ID",
  "A scam message": "একটি প্রতারণার মেসেজ",
  "Raksha will never ask for your OTP, PIN, card number, or password.": "রক্ষা কখনও আপনার OTP, PIN, কার্ড নম্বর বা পাসওয়ার্ড চাইবে না।",
  // Private photo protection
  "Is someone threatening to share your photos?": "কেউ আপনার ছবি ছড়িয়ে দেওয়ার হুমকি দিচ্ছে?",
  "You can act on it here without showing the photo to anyone, including us.": "ছবিটি কাউকে — আমাদেরও — না দেখিয়ে এখানেই ব্যবস্থা নিতে পারেন।",
  "Do NOT send, share, or download any photo or video in order to use this.": "এটি ব্যবহারের জন্য কোনো ছবি বা ভিডিও পাঠাবেন না, শেয়ার করবেন না, ডাউনলোড করবেন না।",
  "Only use a photo that is already on this device.": "এই ডিভাইসে আগে থেকেই থাকা ছবিই ব্যবহার করুন।",
  "Choose the photo to protect": "সুরক্ষিত করার ছবিটি বেছে নিন",
  "A photo will not be shown on this screen": "এই স্ক্রিনে ছবি দেখানো হবে না",
  "Your photo will not leave this device. Only a code made from it is sent, never the photo itself.": "আপনার ছবি এই ডিভাইস ছেড়ে যাবে না। তা থেকে তৈরি একটি কোডই পাঠানো হয়, ছবি কখনও নয়।",
  "You do not have to give your name to use this.": "এটি ব্যবহারের জন্য আপনার নাম দেওয়ার দরকার নেই।",
  "Kept on this device. Not shown, not uploaded.": "এই ডিভাইসেই রাখা হয়েছে। দেখানো হয়নি, আপলোড হয়নি।",
  "Your photo is protected.": "আপনার ছবি সুরক্ষিত।",
  "Open my case": "আমার কেস খুলুন",
  "Copy code": "কোড কপি করুন",
  // Verdict screen
  "What we found": "আমরা যা পেয়েছি",
  "Check something else": "অন্য কিছু যাচাই করুন",
  "Needs caution": "সতর্কতা প্রয়োজন",
  "No match found": "কোনো মিল পাওয়া যায়নি",
  "This is not your fault.": "এটি আপনার দোষ নয়।",
  "Do this now": "এখনই এটি করুন",
  "Has any of this already happened?": "এর মধ্যে কিছু ইতিমধ্যেই ঘটে গেছে?",
  "Money was sent": "টাকা পাঠানো হয়েছে",
  "I shared an OTP, PIN, or password": "আমি OTP, PIN বা পাসওয়ার্ড শেয়ার করেছি",
  "I installed an app or shared my screen": "আমি অ্যাপ ইনস্টল করেছি বা স্ক্রিন শেয়ার করেছি",
  "Private photos or videos are involved": "ব্যক্তিগত ছবি বা ভিডিও জড়িত",
  "None of this has happened yet": "এর কিছুই এখনও ঘটেনি",
  "Why we flagged this": "আমরা কেন এটি চিহ্নিত করেছি",
  "What we cannot tell you": "যা আমরা বলতে পারি না",
  "What they will try next": "তারা এরপর কী করবে",
  "Do not do this": "এটি করবেন না",
  "Have we understood this correctly?": "আমরা কি এটি ঠিকভাবে বুঝেছি?",
  "Nothing has been sent yet.": "এখনও কিছুই পাঠানো হয়নি।",
  "Continue to your report": "আপনার রিপোর্টে এগিয়ে যান",
  "Back to response desk": "প্রতিক্রিয়া ডেস্কে ফিরুন",
  "Back to action board": "অ্যাকশন বোর্ডে ফিরুন",
  "Back to recovery cockpit": "পুনরুদ্ধার ককপিটে ফিরুন",
  "Triage": "প্রাথমিক বাছাই",
  "Tell the story": "ঘটনাটি বলুন",
  "Confirm facts": "তথ্য নিশ্চিত করুন",
  "Act and track": "কাজ করুন ও ট্র্যাক করুন",
  "Step 01 / incident intake": "ধাপ 01 / ঘটনা গ্রহণ",
  "Show us what happened.": "কী ঘটেছে তা জানান।",
  "We will identify the script, explain what may happen next, and prepare the safest response path.": "আমরা প্রতারণার কায়দা চিহ্নিত করব, পরে কী হতে পারে তা ব্যাখ্যা করব এবং সবচেয়ে নিরাপদ প্রতিক্রিয়ার পথ প্রস্তুত করব।",
  "If money is leaving now, call 1930 before you finish this form.": "এখনই টাকা চলে গেলে, এই ফর্ম শেষ করার আগে 1930-এ কল করুন।",
  "Start with the incident record. We will keep the recovery actions in view.": "ঘটনার রেকর্ড দিয়ে শুরু করুন। পুনরুদ্ধারের পদক্ষেপগুলি আমরা সামনে রাখব।",
  "This environment does not transmit reports to authorities.": "এই পরিবেশ কর্তৃপক্ষের কাছে কোনো রিপোর্ট পাঠায় না।",
  "Message": "বার্তা",
  "Voice": "ভয়েস",
  "Screenshot": "স্ক্রিনশট",
  "Number or link": "নম্বর বা লিংক",
  "Private image hash": "ব্যক্তিগত ছবির ফিঙ্গারপ্রিন্ট",
  "Paste the message or conversation": "বার্তা বা কথোপকথন পেস্ট করুন",
  "Tell the story in your own words": "নিজের ভাষায় ঘটনাটি বলুন",
  "Voice language": "ভয়েসের ভাষা",
  "Start recording": "রেকর্ডিং শুরু করুন",
  "Stop recording": "রেকর্ডিং বন্ধ করুন",
  "Transcript": "ট্রান্সক্রিপ্ট",
  "Drop an image here or browse": "এখানে ছবি ছাড়ুন বা ব্রাউজ করুন",
  "Remove image": "ছবি সরান",
  "Local fingerprinting": "স্থানীয় ফিঙ্গারপ্রিন্টিং",
  "Enter a phone number, UPI ID, or link": "ফোন নম্বর, UPI ID বা লিংক দিন",
  "Identifiers are analysed as incident evidence. Never enter real account numbers or OTPs.": "পরিচয়কারীগুলি ঘটনার প্রমাণ হিসেবে বিশ্লেষণ করা হয়। আসল অ্যাকাউন্ট নম্বর বা OTP কখনো দেবেন না।",
  "Analyse this incident": "এই ঘটনাটি বিশ্লেষণ করুন",
  "Create local fingerprint": "স্থানীয় ফিঙ্গারপ্রিন্ট তৈরি করুন",
  "Want to see the complete response path?": "সম্পূর্ণ প্রতিক্রিয়ার পথ দেখতে চান?",
  "Open the example task-scam case": "উদাহরণ টাস্ক-স্ক্যাম কেস খুলুন",
  "Money moving now?": "এখনই টাকা চলে যাচ্ছে?",
  "Call 1930 immediately. This intake can wait.": "এখনই 1930-এ কল করুন। এই ফর্ম পরেও করা যাবে।",
  "Call 1930": "1930-এ কল করুন",
  "Privacy boundary": "গোপনীয়তার সীমা",
  "Text is redacted before model analysis. Uploaded screenshots are temporary analysis inputs. Private-image fingerprints stay local.": "মডেল বিশ্লেষণের আগে টেক্সট সম্পাদনা করা হয়। আপলোড করা স্ক্রিনশট সাময়িক বিশ্লেষণ ইনপুট। ব্যক্তিগত ছবির ফিঙ্গারপ্রিন্ট ডিভাইসেই থাকে।",
  "English, Hindi, and Hinglish input are accepted. Avoid entering real personal information in this environment.": "বাংলাসহ একাধিক ভাষার ইনপুট গৃহীত হয়। এই পরিবেশে আসল ব্যক্তিগত তথ্য দেবেন না।",
  "Case tracking": "কেস ট্র্যাকিং",
  "Find your recovery plan.": "আপনার পুনরুদ্ধার পরিকল্পনা খুঁজুন।",
  "Enter the acknowledgement number from your case record. An example case is available without an account.": "আপনার কেস রেকর্ডের স্বীকৃতি নম্বরটি দিন। অ্যাকাউন্ট ছাড়াই একটি উদাহরণ কেস উপলব্ধ।",
  "Acknowledgement number": "স্বীকৃতি নম্বর",
  "Open case": "কেস খুলুন",
  "Open an example case": "উদাহরণ কেস খুলুন",
  "Threat bulletin / pattern corpus": "হুমকি বুলেটিন / প্যাটার্ন সংগ্রহ",
  "Active scam scripts in the atlas.": "অ্যাটলাসে সক্রিয় প্রতারণার কায়দা।",
  "High risk": "উচ্চ ঝুঁকি",
  "Read playbook": "কায়দা পড়ুন",
  "This is what the evidence suggests.": "প্রমাণ এটাই ইঙ্গিত করে।",
  "Confirm extracted facts": "সংগৃহীত তথ্য নিশ্চিত করুন",
  "Act in the right order.": "সঠিক ক্রমে কাজ করুন।",
  "Review the incident before routing.": "রাউটিংয়ের আগে ঘটনাটি পর্যালোচনা করুন।",
  "Advisory result": "পরামর্শমূলক ফলাফল",
  "Recovery cockpit": "পুনরুদ্ধার ককপিট",
  "Recovery scam warning": "পুনরুদ্ধার প্রতারণা সতর্কতা",
  "A filed report can attract a second scam.": "দায়ের করা অভিযোগ দ্বিতীয় প্রতারণা আকর্ষণ করতে পারে।",
  "No police officer, CBI official, bank representative, or I4C representative should ask for money to release your funds.": "আপনার টাকা মুক্ত করতে কোনো পুলিশ কর্মকর্তা, CBI কর্মকর্তা, ব্যাংক প্রতিনিধি বা I4C প্রতিনিধি টাকা চাইবে না।",
  "Case state": "কেসের অবস্থা",
  "packets prepared": "প্যাকেট প্রস্তুত",
  "facts still open": "তথ্য এখনো বাকি",
  "Call 1930 now": "এখনই 1930-এ কল করুন",
  "Prepare response packets": "প্রতিক্রিয়া প্যাকেট প্রস্তুত করুন",
  "Financial amount": "আর্থিক পরিমাণ",
  "Bank or wallet": "ব্যাংক বা ওয়ালেট",
  "Incident description": "ঘটনার বিবরণ",
  "Freeze through your bank": "আপনার ব্যাংকের মাধ্যমে ফ্রিজ করুন",
  "Preserve evidence before deleting anything.": "কিছু মুছে ফেলার আগে প্রমাণ সংরক্ষণ করুন।",
  "New incident": "নতুন ঘটনা",
};

const MARATHI: Record<string, string> = {
  // Intake (smart input)
  "Step 01 / tell us what happened": "पायरी 01 / काय घडले ते सांगा",
  "Paste anything you received. We work out what it is and check it for you.": "तुम्हाला जे मिळाले ते पेस्ट करा. ते काय आहे हे आम्ही ओळखून तुमच्यासाठी तपासू.",
  "Take as long as you need. Nothing is checked until you choose to continue, and you can ask someone you trust to help you with this.": "तुम्हाला हवा तितका वेळ घ्या. तुम्ही पुढे जाण्याचे ठरवेपर्यंत काहीही तपासले जात नाही. विश्वासू व्यक्तीची मदतही घेऊ शकता.",
  "See a worked example": "एक उदाहरण पहा",
  "What did they send you?": "त्यांनी तुम्हाला काय पाठवले?",
  "A message, a phone number, a UPI ID, or a link. One box takes all of them.": "संदेश, फोन नंबर, UPI ID किंवा लिंक. एकाच बॉक्समध्ये सर्व चालेल.",
  "Speak instead": "बोलून सांगा",
  "Add screenshot": "स्क्रीनशॉट जोडा",
  "Remove": "काढा",
  "Check this for me": "हे माझ्यासाठी तपासा",
  "Checking this...": "तपासत आहोत...",
  "There is a problem": "एक अडचण आहे",
  "Not sure what to paste? Try one:": "काय पेस्ट करावे समजत नाही? एक करून पहा:",
  "A suspicious link": "एक संशयास्पद लिंक",
  "A strange UPI ID": "एक विचित्र UPI ID",
  "A scam message": "एक फसवणुकीचा संदेश",
  "Raksha will never ask for your OTP, PIN, card number, or password.": "रक्षा तुमचा OTP, PIN, कार्ड नंबर किंवा पासवर्ड कधीही मागणार नाही.",
  // Private photo protection
  "Is someone threatening to share your photos?": "कोणी तुमचे फोटो पसरवण्याची धमकी देत आहे?",
  "You can act on it here without showing the photo to anyone, including us.": "फोटो कोणालाही — आम्हालाही — न दाखवता तुम्ही येथे कारवाई करू शकता.",
  "Do NOT send, share, or download any photo or video in order to use this.": "हे वापरण्यासाठी कोणताही फोटो किंवा व्हिडिओ पाठवू नका, शेअर करू नका, डाउनलोड करू नका.",
  "Only use a photo that is already on this device.": "या डिव्हाइसवर आधीच असलेला फोटोच वापरा.",
  "Choose the photo to protect": "सुरक्षित करण्यासाठी फोटो निवडा",
  "A photo will not be shown on this screen": "या स्क्रीनवर फोटो दाखवला जाणार नाही",
  "Your photo will not leave this device. Only a code made from it is sent, never the photo itself.": "तुमचा फोटो या डिव्हाइसच्या बाहेर जाणार नाही. त्यापासून बनलेला केवळ एक कोड पाठवला जातो, फोटो कधीही नाही.",
  "You do not have to give your name to use this.": "हे वापरण्यासाठी तुमचे नाव देण्याची गरज नाही.",
  "Kept on this device. Not shown, not uploaded.": "या डिव्हाइसवरच ठेवले. दाखवले नाही, अपलोड केले नाही.",
  "Your photo is protected.": "तुमचा फोटो सुरक्षित आहे.",
  "Open my case": "माझे प्रकरण उघडा",
  "Copy code": "कोड कॉपी करा",
  // Verdict screen
  "What we found": "आम्हाला हे आढळले",
  "Check something else": "दुसरे काही तपासा",
  "Needs caution": "सावधगिरी आवश्यक",
  "No match found": "जुळणी आढळली नाही",
  "This is not your fault.": "ही तुमची चूक नाही.",
  "Do this now": "हे आत्ताच करा",
  "Has any of this already happened?": "यापैकी काही आधीच घडले आहे का?",
  "Money was sent": "पैसे पाठवले गेले",
  "I shared an OTP, PIN, or password": "मी OTP, PIN किंवा पासवर्ड शेअर केला",
  "I installed an app or shared my screen": "मी अ‍ॅप इन्स्टॉल केले किंवा स्क्रीन शेअर केली",
  "Private photos or videos are involved": "खाजगी फोटो किंवा व्हिडिओ यात आहेत",
  "None of this has happened yet": "यापैकी काहीही अजून घडले नाही",
  "Why we flagged this": "आम्ही हे का चिन्हांकित केले",
  "What we cannot tell you": "आम्ही तुम्हाला काय सांगू शकत नाही",
  "What they will try next": "ते पुढे काय करतील",
  "Do not do this": "हे करू नका",
  "Have we understood this correctly?": "आम्ही हे बरोबर समजलो का?",
  "Nothing has been sent yet.": "अजून काहीही पाठवले गेले नाही.",
  "Continue to your report": "तुमच्या अहवालाकडे सुरू ठेवा",
  "Back to response desk": "प्रतिसाद डेस्कवर परत",
  "Back to action board": "कृती फलकावर परत",
  "Back to recovery cockpit": "पुनर्प्राप्ती केंद्रावर परत",
  "Triage": "प्राथमिक वर्गीकरण",
  "Tell the story": "घटना सांगा",
  "Confirm facts": "तथ्यांची पुष्टी करा",
  "Act and track": "कृती करा व ट्रॅक करा",
  "Step 01 / incident intake": "पायरी 01 / घटना नोंद",
  "Show us what happened.": "काय घडले ते सांगा.",
  "We will identify the script, explain what may happen next, and prepare the safest response path.": "आम्ही फसवणुकीची पद्धत ओळखू, पुढे काय घडू शकते ते सांगू आणि सर्वात सुरक्षित प्रतिसाद मार्ग तयार करू.",
  "If money is leaving now, call 1930 before you finish this form.": "आत्ता पैसे जात असतील तर हा फॉर्म पूर्ण करण्याआधी 1930 वर कॉल करा.",
  "Start with the incident record. We will keep the recovery actions in view.": "घटना नोंदीने सुरुवात करा. पुनर्प्राप्ती कृती आम्ही समोर ठेवू.",
  "This environment does not transmit reports to authorities.": "हे वातावरण अधिकाऱ्यांना तक्रारी पाठवत नाही.",
  "Message": "संदेश",
  "Voice": "आवाज",
  "Screenshot": "स्क्रीनशॉट",
  "Number or link": "नंबर किंवा लिंक",
  "Private image hash": "खाजगी प्रतिमा फिंगरप्रिंट",
  "Paste the message or conversation": "संदेश किंवा संवाद पेस्ट करा",
  "Tell the story in your own words": "तुमच्या शब्दांत घटना सांगा",
  "Voice language": "आवाजाची भाषा",
  "Start recording": "रेकॉर्डिंग सुरू करा",
  "Stop recording": "रेकॉर्डिंग थांबवा",
  "Transcript": "लिप्यंतरण",
  "Drop an image here or browse": "येथे प्रतिमा टाका किंवा ब्राउझ करा",
  "Remove image": "प्रतिमा काढा",
  "Local fingerprinting": "स्थानिक फिंगरप्रिंटिंग",
  "Enter a phone number, UPI ID, or link": "फोन नंबर, UPI ID किंवा लिंक टाका",
  "Identifiers are analysed as incident evidence. Never enter real account numbers or OTPs.": "ओळखपत्रांचे घटना पुरावा म्हणून विश्लेषण होते. खरे खाते क्रमांक किंवा OTP कधीही टाकू नका.",
  "Analyse this incident": "या घटनेचे विश्लेषण करा",
  "Create local fingerprint": "स्थानिक फिंगरप्रिंट तयार करा",
  "Want to see the complete response path?": "संपूर्ण प्रतिसाद मार्ग पाहायचा आहे का?",
  "Open the example task-scam case": "उदाहरण टास्क-स्कॅम केस उघडा",
  "Money moving now?": "आत्ता पैसे जात आहेत का?",
  "Call 1930 immediately. This intake can wait.": "लगेच 1930 वर कॉल करा. ही नोंद थांबू शकते.",
  "Call 1930": "1930 वर कॉल करा",
  "Privacy boundary": "गोपनीयता सीमा",
  "Text is redacted before model analysis. Uploaded screenshots are temporary analysis inputs. Private-image fingerprints stay local.": "मॉडेल विश्लेषणापूर्वी मजकूर संपादित केला जातो. अपलोड केलेले स्क्रीनशॉट तात्पुरते विश्लेषण इनपुट आहेत. खाजगी प्रतिमा फिंगरप्रिंट डिव्हाइसवरच राहतात.",
  "English, Hindi, and Hinglish input are accepted. Avoid entering real personal information in this environment.": "मराठीसह अनेक भाषांचे इनपुट स्वीकारले जाते. या वातावरणात खरी वैयक्तिक माहिती टाकू नका.",
  "Case tracking": "केस ट्रॅकिंग",
  "Find your recovery plan.": "तुमची पुनर्प्राप्ती योजना शोधा.",
  "Enter the acknowledgement number from your case record. An example case is available without an account.": "तुमच्या केस नोंदीतील पावती क्रमांक टाका. खाते नसतानाही एक उदाहरण केस उपलब्ध आहे.",
  "Acknowledgement number": "पावती क्रमांक",
  "Open case": "केस उघडा",
  "Open an example case": "उदाहरण केस उघडा",
  "Threat bulletin / pattern corpus": "धोका बुलेटिन / पद्धत संग्रह",
  "Active scam scripts in the atlas.": "अटलासमधील सक्रिय फसवणूक पद्धती.",
  "High risk": "उच्च धोका",
  "Read playbook": "पद्धत वाचा",
  "This is what the evidence suggests.": "पुरावा हेच सूचित करतो.",
  "Confirm extracted facts": "मिळालेल्या तथ्यांची पुष्टी करा",
  "Act in the right order.": "योग्य क्रमाने कृती करा.",
  "Review the incident before routing.": "रूटिंगपूर्वी घटनेचे पुनरावलोकन करा.",
  "Advisory result": "सल्लागार निकाल",
  "Recovery cockpit": "पुनर्प्राप्ती केंद्र",
  "Recovery scam warning": "पुनर्प्राप्ती फसवणूक इशारा",
  "A filed report can attract a second scam.": "नोंदवलेली तक्रार दुसरी फसवणूक आकर्षित करू शकते.",
  "No police officer, CBI official, bank representative, or I4C representative should ask for money to release your funds.": "तुमचे पैसे सोडण्यासाठी कोणताही पोलीस अधिकारी, CBI अधिकारी, बँक प्रतिनिधी किंवा I4C प्रतिनिधी पैसे मागत नाही.",
  "Case state": "केस स्थिती",
  "packets prepared": "पॅकेट्स तयार",
  "facts still open": "तथ्ये अजून बाकी",
  "Call 1930 now": "आत्ताच 1930 वर कॉल करा",
  "Prepare response packets": "प्रतिसाद पॅकेट्स तयार करा",
  "Financial amount": "आर्थिक रक्कम",
  "Bank or wallet": "बँक किंवा वॉलेट",
  "Incident description": "घटनेचे वर्णन",
  "Freeze through your bank": "तुमच्या बँकेद्वारे फ्रीझ करा",
  "Preserve evidence before deleting anything.": "काहीही हटवण्यापूर्वी पुरावे जतन करा.",
  "New incident": "नवीन घटना",
};

const DICTIONARIES: Record<Exclude<RakshaLanguage, "en">, Record<string, string>> = {
  hi: HINDI,
  ta: TAMIL,
  te: TELUGU,
  bn: BENGALI,
  mr: MARATHI,
};

const originals = new WeakMap<Text, string>();

function translateText(node: Text, dictionary: Record<string, string> | null) {
  const original = originals.get(node) ?? node.data;
  if (!originals.has(node)) originals.set(node, original);
  const leading = original.match(/^\s*/)?.[0] ?? "";
  const trailing = original.match(/\s*$/)?.[0] ?? "";
  const core = original.trim();
  const translated = dictionary?.[core];
  const next = dictionary && translated ? `${leading}${translated}${trailing}` : original;
  if (node.data !== next) node.data = next;
}

function translateTree(root: Node, dictionary: Record<string, string> | null) {
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
    acceptNode(node) {
      const parent = node.parentElement;
      if (!parent || ["SCRIPT", "STYLE", "TEXTAREA", "OPTION", "CODE", "PRE"].includes(parent.tagName)) return NodeFilter.FILTER_REJECT;
      // Never touch subtrees that React translates itself via dictionaries.
      // Writing into React-owned nodes corrupts hydration state and freezes
      // the interface in the wrong language.
      if (parent.closest("[data-raksha-i18n='react']")) return NodeFilter.FILTER_REJECT;
      return (node as Text).data.trim() ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_REJECT;
    },
  });
  const nodes: Text[] = [];
  while (walker.nextNode()) nodes.push(walker.currentNode as Text);
  nodes.forEach((node) => translateText(node, dictionary));
}

export default function SiteLanguageLayer() {
  const { language } = useRakshaLanguage();

  useEffect(() => {
    const dictionary = language === "en" ? null : DICTIONARIES[language as Exclude<RakshaLanguage, "en">];
    let scheduled = false;

    const apply = () => {
      scheduled = false;
      observer.disconnect();
      translateTree(document.body, dictionary);
      observer.observe(document.body, { childList: true, subtree: true, characterData: true });
    };

    const schedule = () => {
      if (scheduled) return;
      scheduled = true;
      window.setTimeout(apply, 120);
    };

    // Re-apply after React re-renders and client-side navigations restore
    // English text nodes, so the chosen language persists across the site.
    const observer = new MutationObserver(schedule);
    const firstPass = window.setTimeout(apply, 700);
    window.addEventListener("popstate", schedule);
    window.addEventListener("raksha:routechange", schedule);

    return () => {
      observer.disconnect();
      window.clearTimeout(firstPass);
      window.removeEventListener("popstate", schedule);
      window.removeEventListener("raksha:routechange", schedule);
    };
  }, [language]);

  return null;
}
